const FETCH_STOCKINFO_REQUEST = 'FETCH_STOCKINFO_REQUEST'
const FETCH_STOCKINFO_SUCCESS = 'FETCH_STOCKINFO_SUCCESS'
const FETCH_STOCKINFO_FAILURE = 'FETCH_STOCKINFO_FAILURE'
const HANDLE_SEARCH = 'HANDLE_SEARCH'